### ISSUE TITLE
java.lang.NoSuchMethodError: 'org.yaml.snakeyaml.LoaderOptions org.yaml.snakeyaml.LoaderOptions.setProcessComments(boolean)'

### ISSUE THREAD

**Issue by KyotoGuru** [foss-mc/Patina#31]
openjdk version "18.0.1.1" 2022-04-22
OpenJDK Runtime Environment (build 18.0.1.1+2-6)
OpenJDK 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)
:/home/container$ java -Xms128M -Xmx2048M -Dsip=95.216.48.148 -Dspt=25612 -XX:+UseSerialGC -Dlog4j2.formatMsgNoLookups=true -Dfml.queryResult=confirm -Dterminal.jline=false -Dterminal.ansi=true -DIReallyKnowWhatIAmDoingISwear=true -Duser.timezone=Europe/Moscow -jar -Dfile.encoding=UTF-8 server.jar nogui
Starting org.bukkit.craftbukkit.Main
System Info: Java 18 (OpenJDK 64-Bit Server VM 18.0.1.1+2-6) Host: Linux 4.19.0-10-amd64 (amd64)
Loading libraries, please wait...
[17:58:19 INFO]: Building unoptimized datafixer
[17:58:21 INFO]: Environment: authHost='https://authserver.mojang.com/', accountsHost='https://api.mojang.com/', sessionHost='https://sessionserver.mojang.com/', servicesHost='https://api.minecraftservices.com/', name='PROD'
[17:58:21 INFO]: Found new data pack file/bukkit, loading it automatically
[17:58:25 INFO]: Loaded 7 recipes
[17:58:28 INFO]: Starting minecraft server version 1.19.2
[17:58:28 INFO]: Loading properties
[17:58:28 ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'org.yaml.snakeyaml.LoaderOptions org.yaml.snakeyaml.LoaderOptions.setProcessComments(boolean)'
at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:98) ~[patina-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patina-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:334) ~[patina-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.help.HelpYamlReader.<init>(HelpYamlReader.java:29) ~[patina-1.19.2.jar:git-Paper-"7207b9f"]
at org.bukkit.craftbukkit.v1_19_R1.help.SimpleHelpMap.<init>(SimpleHelpMap.java:45) ~[patina-1.19.2.jar:git-Paper-"7207b9f"]
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.<init>(CraftServer.java:258) ~[patina-1.19.2.jar:git-Paper-"7207b9f"]
at net.minecraft.server.players.PlayerList.<init>(PlayerList.java:163) ~[patina-1.19.2.jar:git-Paper-"7207b9f"]
at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(DedicatedPlayerList.java:15) ~[patina-1.19.2.jar:git-Paper-"7207b9f"]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:208) ~[patina-1.19.2.jar:git-Paper-"7207b9f"]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1129) ~[patina-1.19.2.jar:git-Paper-"7207b9f"]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:308) ~[patina-1.19.2.jar:git-Paper-"7207b9f"]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:58:28 WARN]: Failed to get system info for World Generation
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.storage.SaveData.B()" because "this.m" is null
at net.minecraft.server.MinecraftServer.lambda$fillSystemReport$16(MinecraftServer.java:1726) ~[patina-1.19.2.jar:git-Paper-"7207b9f"]
at net.minecraft.SystemReport.setDetail(SystemReport.java:62) ~[patina-1.19.2.jar:git-Paper-"7207b9f"]
at net.minecraft.server.MinecraftServer.fillSystemReport(MinecraftServer.java:1725) ~[patina-1.19.2.jar:git-Paper-"7207b9f"]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[patina-1.19.2.jar:git-Paper-"7207b9f"]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:308) ~[patina-1.19.2.jar:git-Paper-"7207b9f"]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:58:28 ERROR]: This crash report has been saved to: /home/container/./crash-reports/crash-2022-09-27_17.58.28-server.txt
[17:58:28 INFO]: Stopping server
[17:58:28 INFO]: Saving worlds
[17:58:28 INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[17:58:28 INFO]: Flushing Chunk IO
[17:58:29 INFO]: Closing Thread Pool
[17:58:29 INFO]: Closing Server

HELP

**Comment by UtoECat** [comment]
I have the same problem on patina 1.19.2 installed from scratch
[crash-2022-09-28_06.19.56-server.txt](https://github.com/PatinaMC/Patina/files/9661179/crash-2022-09-28_06.19.56-server.txt)
Patina 1.19.1 works well
