### ISSUE TITLE
Error with Reflections on Patina, but not on Paper or Purpur

### ISSUE THREAD

**Issue by xGinko** [foss-mc/Patina#35]
When using the following plugin for example: https://github.com/xGinko/NetherCeiling
This error is shown on startup:

```
[19:12:21 ERROR]: Error occurred while enabling NetherCeiling v1.2.1--1.16.5 (Is it up to date?)
[19:12:21 ERROR]: Suspected Plugins: 
[19:12:21 ERROR]:       NetherCeiling{enabled,ver=1.2.1--1.16.5,path=plugins/NetherCeiling-1.2.1--1.16.5.jar}
[19:12:21 ERROR]: Exception details below: 
java.lang.NoSuchMethodError: 'org.reflections.util.FilterBuilder org.reflections.util.FilterBuilder.excludePattern(java.lang.String)'
        at org.reflections.scanners.Scanners$1.<init>(Scanners.java:50) ~[?:?]
        at org.reflections.scanners.Scanners.<clinit>(Scanners.java:48) ~[?:?]
        at me.xginko.netherceiling.NetherCeiling.getDefaultLanguageFiles(NetherCeiling.java:144) ~[?:?]
        at me.xginko.netherceiling.NetherCeiling.reloadLang(NetherCeiling.java:119) ~[?:?]
        at me.xginko.netherceiling.NetherCeiling.onEnable(NetherCeiling.java:51) ~[?:?]
```

Heres the same error with a different plugin using the same method:
https://mcpaste.com/6fe8f3eae328af4555d33bfea10410c7

The methods involved with this error are:

```
public void reloadLang() {
        languageCacheMap = new HashMap<>();
        try {
            File langDirectory = new File(instance.getDataFolder() + File.separator + "lang");
            Files.createDirectories(langDirectory.toPath());
            for (String fileName : getDefaultLanguageFiles()) {
                String localeString = fileName.substring(fileName.lastIndexOf('/') + 1, fileName.lastIndexOf('.'));
                logger.info(String.format("Found language file for %s", localeString));
                LanguageCache langCache = new LanguageCache(localeString);
                languageCacheMap.put(localeString, langCache);
            }
            Pattern langPattern = Pattern.compile("([a-z]{1,3}_[a-z]{1,3})(\\.yml)", Pattern.CASE_INSENSITIVE);
            for (File langFile : langDirectory.listFiles()) {
                Matcher langMatcher = langPattern.matcher(langFile.getName());
                if (langMatcher.find()) {
                    String localeString = langMatcher.group(1).toLowerCase();
                    if(!languageCacheMap.containsKey(localeString)) {
                        logger.info(String.format("Found language file for %s", localeString));
                        LanguageCache langCache = new LanguageCache(localeString);
                        languageCacheMap.put(localeString, langCache);
                    }
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
            logger.severe("Error loading language files!");
        }
    }

    private Set<String> getDefaultLanguageFiles(){
        Reflections reflections = new Reflections("lang", Scanners.Resources);
        return reflections.getResources(Pattern.compile("([a-z]{1,3}_[a-z]{1,3})(\\.yml)"));
    }
```

Reflections reference: https://github.com/ronmamo/reflections

Why is this only happening on Patina? The plugin is working fine on both Paper and Purpur.

**Comment by xGinko** [comment]
Any feedback at all?

**Comment by marlester-dev** [comment]
> Any feedback at all?

It's been a month since the last patina commit. I think the author is busy. @foss-mc

**Comment by xGinko** [comment]
_frustration_

**Comment by xGinko** [comment]
Project/Author dead and feature has long changed by now.
